/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_img_processing_BailingJni */

#ifndef _Included_org_img_processing_BailingJni
#define _Included_org_img_processing_BailingJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_img_processing_BailingJni
 * Method:    processing
 * Signature: (I[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_img_processing_BailingJni_processing
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     org_img_processing_BailingJni
 * Method:    initPath
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_img_processing_BailingJni_initPath
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
